




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.managedbean;

import uk.co.planetbeyond.service.generated.IvrMenuBean;
import com.sleepycat.persist.model.Persistent;

/**
* If any changes needs to be made to the IvrMenuBean, it MUST not be made directly to IvrMenuBean
* Instead the IvrMenuManagedBean should be used to make the changes
*/
@Persistent
public class IvrMenuManagedBean extends IvrMenuBean
{
	private static final long serialVersionUID = -5552304216569840780L;

	/**
	* Make the constructor public so that it can be accessed externally
	*/
	public IvrMenuManagedBean()
	{
		super();
	}
}
