




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.IvrMenuManager;
import uk.co.planetbeyond.service.generated.IvrMenuBean;
import uk.co.planetbeyond.service.managedbean.IvrMenuManagedBean;

/**
* If any change needs to be made to the IvrMenuManager, it MUST not be made directly
* Instead the IvrMenuManagerImpl class should be used to make the changes
*/
public class IvrMenuManagerImpl extends IvrMenuManager 
{
	/**
	* Singleton instance of this class
	*/
	private static IvrMenuManagerImpl singleton = new IvrMenuManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private IvrMenuManagerImpl()
	{
		super();
		
		// set the singleton instance of IvrMenuManagerImpl class in the IvrMenuManager so that
		// IvrMenuManager.getInstance() also points to the singleton instance of IvrMenuManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static IvrMenuManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of IvrMenuManagedBean instead of IvrMenuBean
	*/
	@Override
	public IvrMenuBean createIvrMenuBean()
	{
		return new IvrMenuManagedBean();
	}   
}
